### ISSUE TITLE
Не ищет на русском

### ISSUE THREAD

**Issue by peterkarabinovic** [Sant9Iga/fakeGoogle#1]
Например "Киев" возвращает:
"по запросу ничего не найдено.
такое бывает даже у гугла. Это все экология и стрессы. Введите что то попроще."

**Comment by Sant9Iga** [comment]
уже ищет) странная фигня. под ЮНИКС подобными, запрос на кирилице не надо было переводить в URL-кодировку. а в винде нужно) странная штука
