### ISSUE TITLE
Результат поиска выводиться в неверной кодировке

### ISSUE THREAD

**Issue by peterkarabinovic** [Sant9Iga/fakeGoogle#2]
Например на слово 'Kiev' выводит кракозябры:

РљРёРµРІ вЂ” Р’РёРєРёРїРµРґРёСЏ
ru.wikipedia.org/wiki/РљРёРµРІ
РљРёРµРІ вЂ” С‚Р°РєР¶Рµ Р°РґРјРёРЅРёСЃС‚СЂР°С‚РёРІРЅС‹Р№ С†РµРЅС‚СЂ РљРёРµРІСЃРєРѕР№ РѕР±Р»Р°СЃС‚Рё Рё РљРёРµРІРѕ-
РЎРІСЏС‚Рѕ

**Comment by Sant9Iga** [comment]
кодировки исправил и на вход и на выход.
