### ISSUE TITLE
Папка dist не нужна в репозитории

### ISSUE THREAD

**Issue by peterkarabinovic** [Sant9Iga/fakeGoogle#4]
Пусть ее создает build.xml при сборке,
и соответственно  fakeGoogle.war не нужен в репозитории,
т.к. у мена на машине твой fakeGoogle.war не "деполоется"
пишет "Unsupported major.minor version 52.0"
а если я собираю сам war файл со своим JDK то все ок

**Comment by Sant9Iga** [comment]
исправил
