### ISSUE TITLE
jquery-1.9.1.jar ?

### ISSUE THREAD

**Issue by peterkarabinovic** [Sant9Iga/fakeGoogle#5]
А что это за джарник? он же не нужен, ты ж берешь jquery с "/ajax.googleapis.com"

**Comment by peterkarabinovic** [comment]
Кстати servlet-api.jar тоже в war-файле не нужен, т.к. эти классы есть в самом Tomcat'е
Он нужен только для компиляции, ну т.е. для classpath в таске "compile" в build.xml

Ну это такое.... не принципиально

**Comment by Sant9Iga** [comment]
по поводу jquery - правда) удалил. а вот с сервлетами не компилится, если без него сделать.
